HarvestOnline/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using HarvestOnline.Data;
using HarvestOnline.Models;

using System.Security.Cryptography;
using System.Text;

using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;


namespace HarvestOnline.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult DisplayOrders()
        {
            var display = _context.CheckOutUsers.ToList();

            return View(display);
        }

        public IActionResult EditOrders(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("DisplayOrders");
            }

            var addToCart = _context.CheckOutUsers.Where(i => i.OrderId == id).SingleOrDefault();
            if (addToCart == null)
            {
                return RedirectToAction("DisplayOrders");
            }
            return View(addToCart);
        }
        [HttpPost]
        public IActionResult EditOrders(int? id, CheckOutUser record)
        {
            var CheckOutUsers = _context.CheckOutUsers.Where(i => i.OrderId == id).SingleOrDefault();
            CheckOutUsers.ProductName = record.ProductName;
            CheckOutUsers.TotalPrice = record.TotalPrice;
            CheckOutUsers.DateAdded = DateTime.Now;
            CheckOutUsers.Status = record.Status;

            _context.CheckOutUsers.Update(CheckOutUsers);
            _context.SaveChanges();

            return RedirectToAction("DisplayOrders");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register (AdminUser user)
        {
            if(ModelState.IsValid)
            {
                var check = _context.AdminUsers.FirstOrDefault(s => s.Email == user.Email);

                if (check == null )
                {
                    user.Password = GetMD5(user.Password);

                    _context.AdminUsers.Add(user);
                    _context.SaveChanges();

                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    string msg = "User already Exist!";
                    TempData["Error"] = msg;
                    return RedirectToAction("Register");
                }
            }
            return View();          
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string password, AdminUser user)
        {         
            if (ModelState.IsValid)
            {
                var hashPassword = GetMD5(password);

                var data = _context.AdminUsers.Where(s => s.Email.Equals(email) && s.Password.Equals(hashPassword)).ToList();
                AdminUser admin = new AdminUser();

                admin.Email = email;
                admin.Password = password;

                if (data.Count() > 0)
                {
                    user.Email = data.FirstOrDefault().Email;
                    user.Password = data.FirstOrDefault().Password;

                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    string msg = "Incorrect Login Credentials!";
                    TempData["Error"] = msg;
                    return RedirectToAction("Login");
                }
            }         
            return View();
        }

        public static string GetMD5 (string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for(int i =0; i <targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");
            }
            return byte2String;
        }



     
    }
}

HarvestOnline/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using HarvestOnline.Data;
using HarvestOnline.Models;

using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace HarvestOnline.Controllers
{ 
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(ApplicationDbContext context, UserManager<ApplicationUser>userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var list = _context.Customers.Where(c => c.ApplicationUser == user).ToList();
            return View(list);
        }

        public IActionResult IndexAddress()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var list = _context.Addresses.Where(c => c.Customer == cust).ToList();
            return View(list);
        }
        public IActionResult Home()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }
        public IActionResult CreateProfile()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        [HttpPost]
        public IActionResult CreateProfile(Customer record)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            var check = _context.Customers.FirstOrDefault(s => s.ApplicationUser == user);

            var customer = new Customer();
            if(check == null)
            {
                customer.ApplicationUser = user;
                customer.FullName = record.FullName;
                customer.PhoneNumber = record.PhoneNumber;
                customer.ProfileName = record.ProfileName;
                customer.Gender = record.Gender;
                customer.Birthday = record.Birthday;
                customer.Age = record.Age;

                _context.Customers.Add(customer);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }  
            else
            {
                return RedirectToAction("Index");
            }
           
        }
        public IActionResult CreateAddress()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        [HttpPost]
        public IActionResult CreateAddress(Address record)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            // this retrieves the foreign key id from customer table
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var address = new Address();

            address.Customer = cust;
            address.PostalCode = record.PostalCode;
            address.Region = record.Region;
            address.Province = record.Province;
            address.City = record.City;
            address.Barangay = record.Barangay;
            address.BuildingNo = record.BuildingNo;

            _context.Addresses.Add(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");          
        }

        public IActionResult EditProfile(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            if (customer == null)
            {
                return RedirectToAction("IndexAddress");
            }
            return View(customer);
        }

        [HttpPost]
        public IActionResult EditProfile (int? id, Customer record)
        {
            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            customer.FullName = record.FullName;
            customer.PhoneNumber = record.PhoneNumber;
            customer.ProfileName = record.ProfileName;
            customer.Gender = record.Gender;
            customer.Birthday = record.Birthday;
            customer.Age = record.Age;

            _context.Customers.Update(customer);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }
        
        public IActionResult EditAddress(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            if (id == null)
            {
                return RedirectToAction("IndexAddress");
            }

            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            if (address == null)
            {
                return RedirectToAction("IndexAddress");
            }
            return View(address);
        }

        [HttpPost]
        public IActionResult EditAddress(int? id, Address record)
        {
            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            address.PostalCode = record.PostalCode;
            address.Region = record.Region;
            address.Province = record.Province;
            address.City = record.City;
            address.Barangay = record.Barangay;
            address.BuildingNo = record.BuildingNo;

            _context.Addresses.Update(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            if (customer == null)
            {
                return RedirectToAction("Index");
            }

            _context.Customers.Remove(customer);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteAddress(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("IndexAddress");
            }

            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            if (address == null)
            {
                return RedirectToAction("IndexAddress");
            }

            _context.Addresses.Remove(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }

        public IActionResult DisplayView(String searchby, String search)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);

            var list = _context.Products.ToList();
            if (searchby == "ItemName" && search != null)
            {
                return View(list.Where(x => x.ItemName.Contains(search)).ToList());
            }           
            else
            {
                return View(list);
            }
        }

        public IActionResult About()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Farmers()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Contact()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Help()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult AddToCartDisplay()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);

            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var list = _context.AddToCarts.Where(c => c.Customer == cust).ToList();

            decimal x = 0;
            if(list != null)
            {
                foreach (var item in list)
                {
                    x += item.TotalPrice;
                }
                TempData["Total"] = x;
            }

            return View(list);
        }

        public IActionResult AddToCart(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            Product producto = _context.Products.Where(p => p.ItemId == id).SingleOrDefault();
            return View(producto);
            
        }
        [HttpPost]

HarvestOnline/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Harvest Online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link href="~/css/pagedesign.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3; container-fluid" style="background-color:ghostwhite">
            <div class="container-fluid" style="max-width:1500px">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="list-style-type:none; padding:0;float:right; display:inline-block; font-family:'Courier New', monospace">        
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <img src="~/lib/images/output-onlinejpgtools (1).png" style="height:2em">
                            <div class="dropdown">
                                <button class="dropbtn">Admin</button>
                                <div class="dropdown-content">
                                    <a asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

   
    <div style="margin-bottom:100px; max-width:1500px" class="container-fluid">
        <table style="width:auto">
            <tbody style="margin-top:20px">
                <tr style="display:flex">
                    <td style="float:left; border-radius:8px; background-color:#bdf4a7;">
                        <div style="display:inline; font-family:'Courier New', monospace">
                            <img src="~/lib/images/output-onlinepngtools.png" style="vertical-align:middle" class="position-fixed; text-center">
                            <hr />
                            <div>
                                <h4>
                                    <a asp-area="" asp-controller="Product" asp-action="Index" class="nav-link text-dark">
                                        <img src="~/lib/images/circle-cropped (6).png" style="height:2em;" />Check Inventory
                                    </a>
                                </h4>

                                <h4>
                                    <a asp-area="" asp-controller="Product" asp-action="Create" class="nav-link text-dark">
                                        <img src="~/lib/images/circle-cropped.png" style="height:2em;" /> Add New Product
                                    </a>
                                </h4>

                                <h4>
                                    <a asp-area="" asp-controller="Admin" asp-action="DisplayOrders" class="nav-link text-dark">
                                        <img src="~/lib/images/output-onlinejpgtools (5).png" style="height:2em;" />Track Delivery Status
                                    </a>
                                </h4>



                            </div>

                        </div>
                    </td>
                    <td style="float:left; border-radius:8px; background-color:beige;">
                        <div style="margin:15px 15px 15px 15px">
                            <main role="main" class="pb-3">
                                @RenderBody()
                            </main>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

   
    <footer class="border-top footer text-muted" style="background-color:ghostwhite;">
        <div class="container" style="color:black">
            &copy; 2021 - Harvest Online Inc.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HarvestOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Harvest Online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/css/pagedesign.css" rel="stylesheet" />
 

</head>
<body style="background-color:#FFF8E9">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3; container-fluid" style="background-color:ghostwhite">
            <div class="container-fluid" style="max-width:1500px">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between;">
                    <ul class="navbar-nav flex-grow-1" style="list-style-type:none; padding:0;float:right; display:inline-block; font-family:'Courier New', monospace">
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/lib/images/output-onlinepngtools (1).png" style="height:2em" />Notifications</a>
                        </li>
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Help"><img src="~/lib/images/2e095de08301a57890aad6898ad8ba4c-yellow-circle-question-mark-icon-by-vexels.png" style="height:2em" />Help</a>
                        </li>
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <img src="~/lib/images/output-onlinejpgtools (1).png" style="height:2em">
                            <div class="dropdown">
                                <button class="dropbtn">Log in | Sign in</button>
                                <div class="dropdown-content">
                                    <a asp-area="Identity" asp-page="/Account/Login">User Login</a>

                                    <a asp-area="" asp-controller="Admin" asp-action="Login">Admin Login</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="text-center">
        <img src="~/lib/images/output-onlinepngtools.png" style="vertical-align:middle" class="position-fixed; text-center">
    </div>

    <div class="container-fluid" style="position: relative; font-family: 'Courier New', monospace; flex-grow: 1; margin-bottom: 50px; max-width:1500px">
        @using (Html.BeginForm("DisplayView", "Product", FormMethod.Get))
        {
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "ItemName", true) <text>Products</text>
            <br />
            @Html.TextBox("search")<button type="submit" class="btn btn-success btn-sm; fa fa-search"></button>
            <a asp-area="" asp-controller="Product" asp-action="DisplayView" class="btn btn-warning btn-sm">Display All</a>
        }

        <table width="100%" style="font-size:20px; margin-top:10px; background-color:#C9F8D1 /*#FDD880*/; border-radius:4px">
            <tr style="font-family:'Courier New', monospace; color:#FFFFFF">
                <th width="21%"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a></th>
                <th width="22%"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a></th>
                <th width="22%"><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="DisplayView">Products</a></th>
                <th width="21%"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Farmers">Farmers</a></th>
                <th><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a></th>
            </tr>
        </table>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:ghostwhite; display:block;">
        <div class="container" style="color:black">
            &copy; 2021 - Harvest Online Inc.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HarvestOnline/Views/Shared/_UserLayout.cshtml
@*@model IEnumerable<HarvestOnline.Models.ApplicationUser>*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Harvest Online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/css/pagedesign.css" rel="stylesheet" />


</head>
<body style="background-color:#FFF8E9">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3; container-fluid" style="background-color:ghostwhite">
            <div class="container-fluid" style="max-width:1500px">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between;">
                    <ul class="navbar-nav flex-grow-1" style="list-style-type:none; padding:0;float:right; display:inline-block; font-family:'Courier New', monospace">
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Home"> <img src="~/lib/images/output-onlinepngtools (1).png" style="height:2em" />Notifications</a>
                        </li>
                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Help"><img src="~/lib/images/2e095de08301a57890aad6898ad8ba4c-yellow-circle-question-mark-icon-by-vexels.png" style="height:2em" />Help</a>
                        </li>


                        <li class="nav-item" style="margin: 0px 10px 0px 10px;">
                            <img src="~/lib/images/output-onlinejpgtools (1).png" style="height:2em">
                            <div class="dropdown">
                                <button class="dropbtn">@ViewBag.userId</button>
                                <div class="dropdown-content">
                                    <a asp-area="" asp-controller="User" asp-action="CreateProfile">My Account</a>

                                    <a asp-area="" asp-controller="User" asp-action="AddToCartDisplay">My Purchases</a>

                                    <a asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="text-center">
        <img src="~/lib/images/output-onlinepngtools.png" style="vertical-align:middle" class="position-fixed; text-center">
    </div>

    <div class="container-fluid" style="position: relative; font-family: 'Courier New', monospace; flex-grow: 1; margin-bottom: 50px; max-width:1500px">
        @using (Html.BeginForm("DisplayView", "User", FormMethod.Get))
        {
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "ItemName", true) <text>Products</text>
            <br />
            @Html.TextBox("search")<button type="submit" class="btn btn-success btn-sm; fa fa-search"></button>
            <a asp-area="" asp-controller="User" asp-action="DisplayView" class="btn btn-warning btn-sm">Display All</a>
        }

        <table width="100%" style="font-size:20px; margin-top:10px; background-color:#C9F8D1 /*#FDD880*/; border-radius:4px">
            <tr style="font-family:'Courier New', monospace; color:#FFFFFF">
                <th width="21%"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Home">Home</a></th>
                <th width="22%"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="About">About Us</a></th>
                <th width="22%"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="DisplayView">Products</a></th>
                <th width="21%"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Farmers">Farmers</a></th>
                <th><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Contact">Contact Us</a></th>
            </tr>
        </table>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:ghostwhite; display:block;">
        <div class="container" style="color:black">
            &copy; 2021 - Harvest Online Inc.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>