HarvestOnline/Controllers/CheckOutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


using System.Net;
using System.Net.Mail;
using HarvestOnline.Models;

using Microsoft.EntityFrameworkCore;
using HarvestOnline.Data;

using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace HarvestOnline.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CheckOutController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Mail()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        [HttpPost]
        public IActionResult Mail(Mail record)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            using (MailMessage mail = new MailMessage("harvestonline888@gmail.com", record.Email))
            {
                mail.Subject = "Order Notification";
                string message = "Hello," + "<br/><br/><br/>" + "Thank you for ordering from Harvest Onine" + "<br/><br/>"
                                         + "Once order has been paid we will begin to process your order " + "<br/><br/><br/>"
                                         + "Order created at " + DateTime.Now.ToString("M/d/yyyy") + "<br/><br/><br/>"
                                         + "Payment Options: " + "<br/>"
                                         + "<b>GCASH :</b> " + "09985892212" + "<br/><br/><br/>"
                                         + "<b>Bank Transfer</b>: " + "<br/>"
                                         + "Account Name: Harvest Online" + "<br/>"
                                         + "Account Number: 2017 2016 1234";
                                         

                mail.Body = message;
                mail.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.UseDefaultCredentials = false;
                    NetworkCredential NetworkCred = new NetworkCredential("harvestonline888@gmail.com", "Harvest*15");
                    smtp.EnableSsl = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mail);
                    ViewBag.Message = "Confirmation Sent";
                }
            }
            return View();
        }
    }
}

HarvestOnline/Controllers/HomeController.cs
using HarvestOnline.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HarvestOnline.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Farmers()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Profile()
        {
            return View();
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HarvestOnline/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using HarvestOnline.Data;
using HarvestOnline.Models;

using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace HarvestOnline.Controllers
{ 
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(ApplicationDbContext context, UserManager<ApplicationUser>userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var list = _context.Customers.Where(c => c.ApplicationUser == user).ToList();
            return View(list);
        }

        public IActionResult IndexAddress()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var list = _context.Addresses.Where(c => c.Customer == cust).ToList();
            return View(list);
        }
        public IActionResult Home()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }
        public IActionResult CreateProfile()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        [HttpPost]
        public IActionResult CreateProfile(Customer record)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            var check = _context.Customers.FirstOrDefault(s => s.ApplicationUser == user);

            var customer = new Customer();
            if(check == null)
            {
                customer.ApplicationUser = user;
                customer.FullName = record.FullName;
                customer.PhoneNumber = record.PhoneNumber;
                customer.ProfileName = record.ProfileName;
                customer.Gender = record.Gender;
                customer.Birthday = record.Birthday;
                customer.Age = record.Age;

                _context.Customers.Add(customer);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }  
            else
            {
                return RedirectToAction("Index");
            }
           
        }
        public IActionResult CreateAddress()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        [HttpPost]
        public IActionResult CreateAddress(Address record)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));

            // this retrieves the foreign key id from customer table
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var address = new Address();

            address.Customer = cust;
            address.PostalCode = record.PostalCode;
            address.Region = record.Region;
            address.Province = record.Province;
            address.City = record.City;
            address.Barangay = record.Barangay;
            address.BuildingNo = record.BuildingNo;

            _context.Addresses.Add(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");          
        }

        public IActionResult EditProfile(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            if (customer == null)
            {
                return RedirectToAction("IndexAddress");
            }
            return View(customer);
        }

        [HttpPost]
        public IActionResult EditProfile (int? id, Customer record)
        {
            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            customer.FullName = record.FullName;
            customer.PhoneNumber = record.PhoneNumber;
            customer.ProfileName = record.ProfileName;
            customer.Gender = record.Gender;
            customer.Birthday = record.Birthday;
            customer.Age = record.Age;

            _context.Customers.Update(customer);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }
        
        public IActionResult EditAddress(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            if (id == null)
            {
                return RedirectToAction("IndexAddress");
            }

            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            if (address == null)
            {
                return RedirectToAction("IndexAddress");
            }
            return View(address);
        }

        [HttpPost]
        public IActionResult EditAddress(int? id, Address record)
        {
            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            address.PostalCode = record.PostalCode;
            address.Region = record.Region;
            address.Province = record.Province;
            address.City = record.City;
            address.Barangay = record.Barangay;
            address.BuildingNo = record.BuildingNo;

            _context.Addresses.Update(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var customer = _context.Customers.Where(i => i.CustomerId == id).SingleOrDefault();
            if (customer == null)
            {
                return RedirectToAction("Index");
            }

            _context.Customers.Remove(customer);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteAddress(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("IndexAddress");
            }

            var address = _context.Addresses.Where(i => i.AddressId == id).SingleOrDefault();
            if (address == null)
            {
                return RedirectToAction("IndexAddress");
            }

            _context.Addresses.Remove(address);
            _context.SaveChanges();

            return RedirectToAction("IndexAddress");
        }

        public IActionResult DisplayView(String searchby, String search)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);

            var list = _context.Products.ToList();
            if (searchby == "ItemName" && search != null)
            {
                return View(list.Where(x => x.ItemName.Contains(search)).ToList());
            }           
            else
            {
                return View(list);
            }
        }

        public IActionResult About()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Farmers()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Contact()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult Help()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            return View();
        }

        public IActionResult AddToCartDisplay()
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);

            ApplicationUser user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == _userManager.GetUserId(HttpContext.User));
            var latestCId = _context.Customers.FirstOrDefault(c => c.ApplicationUser == user).CustomerId;
            Customer cust = _context.Customers.FirstOrDefault(c => c.CustomerId == latestCId);

            var list = _context.AddToCarts.Where(c => c.Customer == cust).ToList();

            decimal x = 0;
            if(list != null)
            {
                foreach (var item in list)
                {
                    x += item.TotalPrice;
                }
                TempData["Total"] = x;
            }

            return View(list);
        }

        public IActionResult AddToCart(int? id)
        {
            ViewBag.userId = _userManager.GetUserName(HttpContext.User);
            Product producto = _context.Products.Where(p => p.ItemId == id).SingleOrDefault();
            return View(producto);
            
        }
        [HttpPost]

HarvestOnline/Views/User/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Objectives</h2>
<section class="container-fluid">
    <div>
        <div style="margin-top:30px; float:left; position:fixed; width:100%; max-width:500px; height:auto">
            <section>
                <p><mark style="background-color:antiquewhite">To provide fresh and handpicked fruits and vegetables to every consumer in the country.</mark></p>
            </section>

            <section style="margin-top:30px">
                <p><mark style="background-color:antiquewhite">To aim to champion our local farmers and work closely with them in order to give them</mark></p>
                <p><mark style="background-color:antiquewhite">better opportunities by introducing to them better technology and methods to market their</mark></p>
                <p><mark style="background-color:antiquewhite">products online.</mark></p>
            </section>

            <section style="margin-top:30px">
                <p><mark style="background-color:antiquewhite">To value consumers lifestyle that is why we are committed to sustain their health by</mark></p>
                <p><mark style="background-color:antiquewhite">providing them fresh products that gives them nutrition and good health.</mark></p>
            </section>

            <section style="margin-top:30px">
                <p><mark style="background-color:antiquewhite">To improve the lives of our local farmers and to our consumers.</mark></p>
            </section>
        </div>

        <div style="float:right">
            <img src="~/lib/images/farmers-give-up-on-us-july-9-2017.jpg" />
        </div>
    </div>
</section>

HarvestOnline/Views/User/AddToCart.cshtml
@model HarvestOnline.Models.Product

@{
    ViewData["Title"] = "AddToCart";
    ViewBag.Title = "AddToCart";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using (@Html.BeginForm())
{
<div class="container">
    <div class="row">
        <div class=" col-lg-10 col-md-10 col-sm-10">
            <img style="min-height: 200px; width:200px" src="@Url.Content(Model.ImagePath)" />
        </div>

        <div>
            <h1>Product Name: @Model.ItemName</h1>
            <h1>Product Price: @Model.Price</h1>
            <h1>Product Selling Qty: @Model.ItemSellingQuanity</h1>
            <input type="number" name="qty" value="1" min="1" id="qty" />
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </div>
</div>
}

HarvestOnline/Views/User/AddToCartDisplay.cshtml
@model IEnumerable<HarvestOnline.Models.AddToCart>

@{
    ViewData["Title"] = "AddToCartDisplay";
    Layout = "~/Views/Shared/_UserLayout.cshtml";

}

<h1>Purchases</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" style="color:red; font-family:'Franklin Gothic Book'"> <h1>Cart is Empty</h1></td>
            </tr>
        }
        else
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductImage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        <a asp-action="DeleteItem" asp-route-id="@item.CartId">Delete</a>
                    </td>
                    <td>
                        <a asp-action="Purchase" asp-route-id="@item.CartId">Check Out</a>
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3"></td>
            <td><b>Total</b></td>
            <td>@TempData["Total"]</td>
        </tr>
    </tfoot>
</table>

HarvestOnline/Views/User/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Contact Us</h2>
<section class="container-fluid">
    <div style="margin-top:30px; float:left; position:fixed">
        <section>
            <p><b>General Inquiries</b></p>
            <p>General enquries about the Harvest Online should be sent to harvestonline.ph@gmail.com</p>
        </section>

        <section style="margin-top:30px">
            <p><b>Press and media</b></p>
            <p>For press releases, media or advocacy related inqueries, kindly email pressmedia@gmail.com</p>
        </section>

        <section style="margin-top:30px">
            <p><b>Like our page on Facebook</b></p>
            <p>http://www.facebook.com/harvestonlineph/</p>
        </section>

        <section style="margin-top:30px">
            <p><b>Follow us on Instagram</b></p>
            <p>http://www.instagram.com/harvestonlineph/?hl=en</p>
        </section>

        <section style="margin-top:30px">
            <p><b>Chat with Us on Whatsapp or Telegram</b></p>
            <p>0996582147</p>
        </section>
    </div>
</section>

HarvestOnline/Views/User/CreateAddress.cshtml
@model HarvestOnline.Models.Address

@{
    ViewData["Title"] = "CreateAddress";
    Layout = "~/Views/Shared/_UserDashLayout.cshtml";
}

<h1>CreateAddress</h1>

<h4>Address</h4>
<hr />
<div class="container-fluid" style="display:flex; flex:1">
    <div class="row" style="margin-right: 20px; width: 760px">
        <div class="col-md-12" style="font-family:Courier New, Courier, monospace; margin:25px 25px 25px 25px">
            <form asp-action="CreateAddress">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PostalCode" class="control-label"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Region" class="control-label"></label>
                    <select asp-for="Region" class="form-control" asp-items="Html.GetEnumSelectList<Region>()"></select>
                    <span asp-validation-for="Region" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Province" class="control-label"></label>
                    <input asp-for="Province" class="form-control" />
                    <span asp-validation-for="Province" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Barangay" class="control-label"></label>
                    <input asp-for="Barangay" class="form-control" />
                    <span asp-validation-for="Barangay" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BuildingNo" class="control-label"></label>
                    <input asp-for="BuildingNo" class="form-control" />
                    <span asp-validation-for="BuildingNo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HarvestOnline/Views/User/CreateProfile.cshtml
@model HarvestOnline.Models.Customer

@{
    ViewData["Title"] = "CreateProfile";
    Layout = "~/Views/Shared/_UserDashLayout.cshtml";

}

<h1>Create Profile</h1>

<h4>Customer</h4>
<hr />
<div class="container-fluid" >
    <div class="row" style="margin-right: 20px; width: 760px">
        <div class="col-md-12" style="font-family:Courier New, Courier, monospace; margin:25px 25px 25px 25px">
            <form asp-action="CreateProfile">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProfileName" class="control-label"></label>
                    <input asp-for="ProfileName" class="form-control" />
                    <span asp-validation-for="ProfileName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    <select asp-for="Gender" class="form-control" asp-items="Html.GetEnumSelectList<Gender>()"></select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Birthday" class="control-label"></label>
                    <input asp-for="Birthday" class="form-control" />
                    <span asp-validation-for="Birthday" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Show Personal Info</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HarvestOnline/Views/User/DisplayView.cshtml
@model IEnumerable<HarvestOnline.Models.Product>

@{
    ViewData["Title"] = "DisplayView";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<section style="margin-bottom: 70px;" class="container-fluid">
    <div style="margin-top: 30px; background-color: #f1fdf3; border-radius: 5px;">
        <table style="display: grid; grid-template-columns: auto auto auto auto; margin:0px 0px 0px 90px">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="4" style="color:red; font-family:'Franklin Gothic Book'"> No rows match the Search Criteria!</td>
                </tr>
            }
            else
            {
                @foreach (var item in Model)
                {
                    <tbody style="margin-top:20px;  margin-bottom:20px; font-family:'Lucida Console'">
                        <tr>
                            <td style="padding:5px 5px 5px 5px; background-color:#FBF8ED ;border-radius:8px;">
                                <figure style="text-align:center;">
                                    <img style="width:240px; height:200px; border-radius:10px; margin-bottom:30px" src="@Url.Content(item.ImagePath)" />
                                    <figcaption>@Html.DisplayFor(modelItem => item.ItemName)</figcaption>
                                    <figcaption style="color:limegreen;">@Html.DisplayFor(modelItem => item.Price)</figcaption>
                                    <figcaption style="margin-top:30px"><span class="btn btn hover btn btn-secondary" style="background-color:#ecf0dd; 
                                                border-radius:8px; border-color:black">@Html.ActionLink("Add to Cart", "AddToCart", new { id = item.ItemId })
                                                </span></figcaption>
                                </figure>
                            </td>
                        </tr>
                    </tbody>
                }
            }
        </table>
    </div>
</section>

HarvestOnline/Views/User/Help.cshtml
@{
    ViewData["Title"] = "Help";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<div class="container-fluid">
    <p>Hi there!</p>
    <p>
        If you would like to be a part of the Harvest Online Vendors please feel free to contact us at: <br />
        <b>Email:</b> harvestonline.ph@gmail.com <br />
        <b>Telephone Number:</b> (02) 8881 - 2345 <br />
        <b>Cellphone Number:</b> (0921) 623 4420 <br />

        <br />
        <br />

        If you have questions in regards with website please feel free to contact our customer service! <br />
        <b>Messenger :</b> https://www.messenger.com/t/10000127325421112/ <br />
        <b>Viber: </b> (0991) 512 4420 <br />
        <b>Facebook Group: </b> http://www.facebook.com/harvestonlineph-community/

        <br />
        <br />

        Thank you and God Bless!
    </p>
</div>

HarvestOnline/Views/User/Purchase.cshtml
@model HarvestOnline.Models.AddToCart

@{
    ViewData["Title"] = "Check Out";
    ViewBag.Title = "Purchase";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<h1>Purchased</h1>
@using (@Html.BeginForm())
{
    <div class="container">
        <div class="row">
            <div>
                <h1>Product Name: @Model.ProductName</h1>
                <h1>Product Price: @Model.TotalPrice</h1>
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

HarvestOnline/Views/User/PurchaseView.cshtml
@model IEnumerable<HarvestOnline.Models.CheckOutUser>

@{
    ViewData["Title"] = "PurchaseView";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>Purchase View</h1>
<a asp-area="" asp-controller="CheckOut" asp-action="Mail" style="color:red">Click Here for Payment Options</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShippingFee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPayment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" style="color:red; font-family:'Franklin Gothic Book'"> <h1>Cart is Empty</h1></td>
            </tr>
        }
        else
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShippingFee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPayment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAdded)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>